### ISSUE TITLE
Google summer of code application through INCF

### ISSUE THREAD

**Issue by KirstieJane** [INCF/bids-starter-kit#10]
From the [GSoC website](https://summerofcode.withgoogle.com/):

> Google Summer of Code is a global program focused on bringing more student developers into open source software development. Students work with an open source organization on a 3 month programming project during their break from school.

The BIDS parent organisation INCF are participating again as a host GSoC organisation. More information can be found at https://www.incf.org/collaborate/tool-development/google-summer-of-code.

If we want to have a great student working on a project for the bids-starter-kit in the summer we need to submit an application to INCF by **January 15th 4pm CET**.

Here's a list of the current draft proposals to give us an idea of what a proposal looks like! https://www.incf.org/collaborate/tool-development/google-summer-of-code/gsoc-2017-project-ideas

Below I've outlined an idea for how a GSoC student could support the development of the bids-starter-kit. Please share any comments, suggestions & additions!

---

### Vision

To build up a set of tutorials for BIDS that are housed in [jupyter notebooks](http://jupyter.org/) (which don’t have to be written in python) and enable [mybinder](https://mybinder.org/) integration so they are fun and interactive ways to learn about BIDS. We're particularly inspired by the [Nipype tutorials](https://miykael.github.io/nipype_tutorial/) built by @miykael.

The student would also be integral in building up a community of BIDS users - in particular supporting new and and code nervous folk who just want to do their studies and don’t really care about how they name their files…but who want to do good reproducible science at the same time :)

### Timeline

Three stages: 1) collecting together knowledge from current users and developers, 2) turning this information into interactive notebooks, and 3) soliciting feedback from potential users as to what else they want to see. (You could also imagine iterating around 2 and 3 a few times in a best case scenario!)

### Mentors

I (Kirstie Whitaker) am happy to be the point person for this - but also very happy for anyone else to take the lead.

I have no opinions on whether it's good to name more than one mentor, but importantly there will certainly be **LOTS of opportunities** for everyone in the current BIDS community to support the student and build the project together! 
  
---

### To do list

- [x] Find out the deadline for submissions to INCF
  * Done by CG on Christmas eve 🎄 and reply recieved on Christmas day 🎅 
  * ***January 15 4pm Swedish time***
- [x] Email Malin at INCF to see what the requirements are for GSoC submissions within INCF
  * Done by KW on 5th Jan (late on Friday) - reply received on 6 Jan
- [x] Find a great picture to go with the application (because everyone likes pictures)
  * Added image from Sci Data paper, no porgs, but probably more informative...
- [x] Write the draft - started by @emdupre - available at: https://docs.google.com/document/d/1xkZhCWv-y3QAigzq-vDYJzzMUkQygxBXy8f1s2UoBao/edit?usp=sharing
- [x] Send information to Malin

**Comment by choldgraf** [comment]
I am happy to help out with mentorship/guidance, but don't have bandwidth for a point-person position on this. I think it's a great idea!

**Comment by KirstieJane** [comment]
Thanks @choldgraf! :sparkles:

**Comment by KirstieJane** [comment]
Some notes from our google hangout just now:

* This project is really great for any students looking to build their **community development** and **user support** skills. It will still have some fun coding aspects: building the notebooks and making them interactive, but the longest running effects for the student is likely to be 1) **real world experience** engaging with a wide range of researchers and developers and 2) experience with **design thinking** for open innovation (see Lorraine Cheun's [webinar](https://www.youtube.com/watch?v=mQUAq6zsqRg) & [slides](https://docs.google.com/presentation/d/1qMNS2-AtnvZPldGoBRitRq-IVrHUNUp1aedys7kOz3M/edit#slide=id.g28e2d6f38c_0_66) for more information).

* Here's a useful mentor guide for GSoC: https://google.github.io/gsocguides/mentor/#a-brief-history-of-google-summer-of-code

* Although there are many possible candidate students, have a think about reaching out to PhD students in the field of neuroimaging who might want to take this on!

* There {will, may} be three other (four total) BIDS GSoC projects and that would allow the GSoC student to build a mini community within the larger BIDS community as they get started on their specific projects. This might be a good reason for someone looking to build their community management experience to join this project.

* @dorahermes is working with collaborators who will be needing to get their data into BIDS format by the summer, which is perfect timing for our student to engage with them and understand what their needs are.

* We also have great experience within the BIDS community about what questions tend to come up from the members who have lead **Intro to BIDS** workshops. They are an excellent jumping off point for thinking about what information newcomers to BIDS need.

* Interactive notebooks are just way more fun than reading 📖 🎮 👾

**Comment by emdupre** [comment]
Just to add, the experience with neuroimaging (or at least basic familiarity) is one possible asset, but undergrad or masters students with this background would be equally well-suited!

**Comment by KirstieJane** [comment]
Ok thread! The application looks great to me - I'm happy to send it off on Monday morning (swooshing in before the deadline 😬)

**Comment by emdupre** [comment]
I think this can be closed ! We should, though, open an issue on how students can show interest in / fit for this GSoC project (since INCF was accepted as a mentor organization ! 🎉).

**Comment by dorahermes** [comment]
What about: "Template needed for _events.tsv file?"

**Comment by emdupre** [comment]
Opened in #13 !

**Comment by KirstieJane** [comment]
Closing! We got a great GSoC student!! ✨ 👾 💯 @Park-Patrick
