### ISSUE TITLE
Chat communications

### ISSUE THREAD

**Issue by KirstieJane** [INCF/BIDS-Starter-Kit#11]
We seem to be very happily using GitHub issues for our discussions, but I wonder if we could also supplement these with either a gitter chat room or a slack channel in the [brainhack workspace](https://brainhack.slack.com/messages/C0GSFN4H1/)?

**Comment by satra** [comment]
@KirstieJane - I very much like this over realtime communication for discussions as there is a consistent theme, generally no intertwining of information and viewable and searchable history. people can watch/unwatch issues and respond to them via email.

these can often be linked to projects (btw, github projects is really a very nice tool for managing project flows).

**Comment by KirstieJane** [comment]
I totally hear you @satra that issues & GitHub projects are awesome for actually taking the work forwards. I’m just thinking that I don’t personally know some of the contributors here and I’d like to!

One reason I like gitter is that it’s not very easy to have great big long planning discussions there, it gets quite hard to scroll back quite quickly. For me this is a plus because you don’t get tempted to actually do the proper work relating to the project there, but I still love being able to say hi and hello to new contributors for the other projects I contribute to.

Beyond my personal preference for wanting to get to know folk here (and in the future) better, I do think that having a place where it’s very easy for new contributors to ask “silly” questions is really valuable.

Interested to know what others think though, and happy to keep discussions in GitHub issues for now 🌺

**Comment by dorahermes** [comment]
+1 to a brainhack slack channel (with the note that I sometimes forget to check that for a couple of days, and need to be pinged to respond)

**Comment by KirstieJane** [comment]
Reawakening an old thread - we have a gitter channel: https://gitter.im/INCF/bids-starter-kit and a channel in the slack workspace: https://brainhack.slack.com/messages/C8RG7F6PN.

At the moment the `Chat` link in the [README](https://github.com/INCF/bids-starter-kit/blob/master/README.md) goes directly to the gitter channel. This is fine but I think we should add a little more content to the [Contributing](https://github.com/INCF/bids-starter-kit/blob/master/README.md#contributing) section of the README.

Something like: 

> We have lots of different ways of staying in touch! You can ask us any questions via our [gitter channel](https://gitter.im/INCF/bids-starter-kit), or in the [bids-starter-kit channel](https://brainhack.slack.com/messages/C8RG7F6PN/) in the [Brainhack slack workspace](https://brainhack.slack.com/). If you aren't a member of that slack team you can join via [INSERT LINK HERE!]

**Comment by Park-Patrick** [comment]
Sounds good. Here's the link to the get an invite for the slack channel:
https://brainhack-slack-invite.herokuapp.com/ 
and happy to add to the readme as well too

**Comment by chrisfilo** [comment]
Is this intended to be chat for discussing the development of the starter kit or a general support channel for people to ask questions about BIDS?

**Comment by Park-Patrick** [comment]
Following discussion (@KirstieJane , @chrisfilo , @Park-Patrick) over snacks at the hackathon:

the advantage of chat (gitter / slack) is that it feels more welcoming (lower barrier to entry)

the advantage of forums is that the same question doesn't have to be answered twice
-- so this would be more scaleable if the community grows

So basically, we want to encourage people to use Neurostars, but for additional help they can go to the chats too.

To be added to README Contributing section:

We have lots of different ways of staying in touch! You can come chat via our [gitter channel](https://gitter.im/INCF/bids-starter-kit) or [slack](https://brainhack.slack.com/messages/C8RG7F6PN/details/ )
If you aren't a member of the slack team you can join via https://brainhack-slack-invite.herokuapp.com/ 

or please send an email to the mailing list to be added: bids-discussion@googlegroups.com 

Our **preferred** way to answer questions is via our forum Neurostars (we have a 90%+ answer rate!)
We understand that posting a question on a forum can seem a bit uncertain and intimidating. 
However, if _you_ have a question it's almost certain that somebody else will too, and this way we can avoid answering the same question multiple times.
Even if your question is not well-defined, just post what you have so far and we will be able to point you in the right direction!

**Comment by KirstieJane** [comment]
Lolz - I didn't realise that I was all powerful and could edit @Park-Patrick's comments! 💪 🔥 😆 

Now it contains all the minor formatting updates that I like!

I think this looks great. @chrisfilo - do you think it gets the point about Neurostars across clearly?

**Comment by Park-Patrick** [comment]
Bumping this issue up again ⬆️ 

If we're okay to move forward with the descriptions above, may I suggest we create a central "Contact" page that can be linked to? This would be to address the problem of having the same text copied in a bunch of different places in the repo (i.e. already its in the README, wiki, contributing guidelines etc.).

If we ever decide to update the contact info / policies we may end up with a lot of similar but not same text and broken links

**Comment by emdupre** [comment]
I like the idea of a contact page ! So long as all of the resources you listed @Park-Patrick (i.e., README, CONTRIBUTING, wiki) point to it, I think it would be great in helping to make sure everything stays up to date :+1:

**Comment by Park-Patrick** [comment]
Okay we have a central page with our contact info / preferences now!
 https://github.com/INCF/BIDS-Starter-Kit/wiki/Contact.

**Comment by emdupre** [comment]
:tada: thanks, @Park-Patrick  !
Can you have the home page of the wiki link to the contact page, too ? Right now it just links out to gitter and slack

**Comment by Park-Patrick** [comment]
Right! Thanks for spotting that

**Comment by KirstieJane** [comment]
Looks great! Thank you @Park-Patrick
