### ISSUE TITLE
Add link to BIDS conversion tutorial written by Franklin

### ISSUE THREAD

**Issue by chrisfilo** [INCF/bids-starter-kit#12]
http://reproducibility.stanford.edu/bids-tutorial-series-part-1a/

**Comment by emdupre** [comment]
I was just about to open this issue ! Just curious, what was your reasoning to not add it ?

**Comment by chrisfilo** [comment]
@franklin-feingold already added it to the wiki

**Comment by emdupre** [comment]
Thanks, sorry ! Not yet used to working without pull requests.
