### ISSUE TITLE
Add template for _events.tsv file in the func data

### ISSUE THREAD

**Issue by dorahermes** [INCF/bids-starter-kit#13]
We do not have a template yet for the _events.tsv file. The best place is probably to add this for the func dataset.

**Comment by martxyz** [comment]
Hi @dorahermes ,

I can do that (: 

Using the same style of: https://github.com/INCF/bids-starter-kit/blob/master/matlabCode/createBIDS_participants_tsv.m

We want something like that: https://github.com/INCF/bids-starter-kit/blob/master/templates/participants.tsv

If i misunderstanding something, please tell me.
Thanks

**Comment by dorahermes** [comment]
exactly, that would be great, thanks!

**Comment by martxyz** [comment]
Great!

Will do!

Can you assign me to this issue?

**Comment by martxyz** [comment]
Hello, not finding which fields we need to put in the .m to generate the tsv.

**Comment by dorahermes** [comment]
See BIDS spec section 8.4:
https://docs.google.com/document/d/1HFUkAEE-pB-angVcYe6pf_-fVf4sCpOHKesUvfb8Grc/edit#

I am not sure how to assign you here... your name does not pop up if I try...

**Comment by emdupre** [comment]
Only organization members can be directly assigned, I think. But thanks for starting on this, @martxyz ! 🌟

**Comment by martxyz** [comment]
https://github.com/martxyz/matlab
