### ISSUE TITLE
Add template for the _meg.json file

### ISSUE THREAD

**Issue by dorahermes** [INCF/bids-starter-kit#16]
Would be great to have code and templates for the MEG specification

**Comment by cofficer** [comment]
Hey @dorahermes ,

I would happily tackle this! I'm just reading into the specifications. 

Cheers,
Christoffer Gahnström

**Comment by dorahermes** [comment]
great, thank you! please post any questions that come up

**Comment by cofficer** [comment]
I just made a pull request, first doing one, hope I went about it correctly!

**Comment by cofficer** [comment]
Should I also add the .json template created by this script to the pull request? Which would in the path: templates/sub-01/sess-01/meg/*.json

**Comment by dorahermes** [comment]
Thank would be great, thank you! The path is correct (small typo - ses with 1 s):
templates/sub-01/ses-01/meg/
and filename:
sub-01_ses-01_task-LongExample_run-01_meg.json
(LongExample because it has all the fields)

**Comment by emdupre** [comment]
Closed in #31
