### ISSUE TITLE
Create python file to generate dataset description template 

### ISSUE THREAD

**Issue by anushkab** [INCF/bids-starter-kit#19]
A python file required to generate dataset description json file.

**Comment by anushkab** [comment]
Hey @dorahermes 
I have been through the specifications and I would like to work on this.
Regards
Anushka

**Comment by emdupre** [comment]
It would be great to have a python script to generate the dataset description ! We have a template json file [here](https://github.com/INCF/bids-starter-kit/blob/master/templates/dataset_description.json). 

Feel free to open a pull request with this, and let us know if you need any help !

**Comment by anushkab** [comment]
The different packages (Fieldtrip/MNE) have a lot to offer in creating a python script .
But for simplicity of the starter kit would it be advisable to make simple python scripts to generate the json tsv templates ?

**Comment by KirstieJane** [comment]
Hi @anushkab - I think for now we're better off focusing on the documentation and the tutorials rather than building new scripts.

I think, since #20 was merged, we can close this issue?

**Comment by anushkab** [comment]
Yeah 
I am closing the issue right away.
