### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by chrisfilo** [INCF/bids-starter-kit#2]
Describe how one can contribute to this repository

https://opensource.guide/how-to-contribute/#how-to-submit-a-contribution
https://github.com/emdupre/me-ica/blob/py3/CONTRIBUTING.md

We need to add extra lines about the wiki

**Comment by dorahermes** [comment]
I noticed that in the BIDS repo contributors are recognized in the BIDS spec (https://docs.google.com/document/d/1HFUkAEE-pB-angVcYe6pf_-fVf4sCpOHKesUvfb8Grc/edit#heading=h.hds2i7ii7hjo). @chrisfilo do you have a good suggestion of where to recognize bids-starter-kit contributors?

**Comment by chrisfilo** [comment]
I would recommend it goes into the same place. This will ensure highest
visibility for all contributors.

Best,
Chris

**Comment by choldgraf** [comment]
+1 to piggy-backing on pre-existing material. We don't wanna fracture too much!

**Comment by dorahermes** [comment]
Done (and I added @choldgraf and me as contributors in the BIDS spec ;)

**Comment by choldgraf** [comment]
yay!
--
