### ISSUE TITLE
Link other relevant resources

### ISSUE THREAD

**Issue by emdupre** [INCF/BIDS-Starter-Kit#25]
@choldgraf pointed out that [mne-tools](https://github.com/mne-tools/mne-bids) would be a good resource to keep in mind as we're developing this starter kit. In #10, we also discussed the structuring these resource to resemble [nipype tutorials](https://github.com/miykael/nipype_tutorial) format.

It would be great to update the README (or the wiki) to link out to these resources and any others that might be helpful ! Is there a preference on which, @dorahermes ?

**Comment by dorahermes** [comment]
I imagine the list with links may grow quite long and it would be nice to have that on the wiki and keep the readme short. I just updated the readme that links to other relevant resources will be described in the wiki.

**Comment by KirstieJane** [comment]
I'm good with keeping links in the wiki.

When someone has time, we could make a new "clean" issue (or just update this one) and leave it open as a "good first bug" so that new folks can add resources they know about to the wiki and feel like they're being AWESOME contributors (because they are!!)

**Comment by chrisfilo** [comment]
Is there a page on the wiki dedicated to listing all of the external tutorials? @Park-Patrick

**Comment by chrisfilo** [comment]
Could the link from the README link to the new wiki page? Right now it links to CRN blog which will feature content beyond BIDS tutorials.

**Comment by dorahermes** [comment]
+1 on new wiki page with links to tutorials

**Comment by Park-Patrick** [comment]
Edited the link on the README to point to the new wiki-tutorial page and added individual links to the tutorials (instead of just the CRN blog).

**Comment by chrisfilo** [comment]
Thanks!
Best,
Chris

**Comment by KirstieJane** [comment]
@Park-Patrick - 👍 on tidying up the issues & separating them into different tasks 👾
