### ISSUE TITLE
Google Summer of Code Applicants. 

### ISSUE THREAD

**Issue by joanrue** [INCF/bids-starter-kit#26]
This issue is intended to comment our interest and share advice during the application process for the **2018 GSoC**.

**Comment by emdupre** [comment]
Thanks for opening this, @joanrue ! I'd also recommend that anyone interested also check out the project on Trellis (email gsoc@incf.org if you don't yet have access), as we've had some helpful discussions there.

Generally, make sure to take a look at the [INCF 2018 GSoC webpage](https://www.incf.org/activities/training/gsoc-2018-project-ideas) for FAQs, student guide, and application timeline !

**Comment by emdupre** [comment]
Also, take a look at #10 ! @KirstieJane really nicely laid out some of our early discussions on our vision / goals for this GSoC project.

**Comment by KirstieJane** [comment]
Thanks @joanrue & @emdupre!

If anyone else is dropping by, make sure to get your application uploaded to the GSOC portal at https://summerofcode.withgoogle.com by the deadline on 27th March! SOON!
