### ISSUE TITLE
Full example vs Short example json template differences

### ISSUE THREAD

**Issue by Park-Patrick** [INCF/bids-starter-kit#30]
Hi @dorahermes @emdupre @KirstieJane 

I just noticed that the template json file for the full example and short example are identical.

File paths: 
bids-starter-kit/templates/sub-01/ses-01/func/sub-01_ses-01_task-FullExample_run-01_bold.json
bids-starter-kit/templates/sub-01/ses-01/func/sub-01_ses-01_task-ShortExample_run-01_bold.json

Is this something we would like to work on / clarify? 

Happy to be the person to do so if we decide to!

Patrick

**Comment by emdupre** [comment]
Hi @Park-Patrick ! That's a great catch. 👍  I think it would be worth having the `ShortExample` include only mandatory fields (as listed in the [BIDS spec](http://bids.neuroimaging.io/bids_spec1.0.2.pdf)), but continue to have all fields in the `FullExample`. 

Do you think you could open a PR implementing this?

**Comment by Park-Patrick** [comment]
Hi @emdupre sounds good!

I'll simplify the short example and keep the full example as is.

**Comment by Park-Patrick** [comment]
#32 Hi @emdupre the fix is in pull request 32

**Comment by emdupre** [comment]
Closed in #32
