### ISSUE TITLE
Make Kirstie an admin on this repo

### ISSUE THREAD

**Issue by KirstieJane** [INCF/bids-starter-kit#38]
I'm very happy to mentor the BIDS starter kit development - specifically as relates to the GSoC project - but I'm not an admin on this repo. Could anyone make that happen? @dorahermes @choldgraf?

**Comment by choldgraf** [comment]
actually I believe I am not an admin as well, so whoever adds @KirstieJane please add me too... @chrisfilo may have rights as well so pinging him too

**Comment by emdupre** [comment]
I think @dorahermes and I are both collaborators, too ! @chrisfilo might be the owner, iirc....

**Comment by chrisfilo** [comment]
You are all admins now - sorry for that!

**Comment by KirstieJane** [comment]
ALL THE POWAAAAAAR :wink:

Thanks @chrisfilo!

**Comment by choldgraf** [comment]
![](https://media.giphy.com/media/3ornk7nts29Am5LIfm/giphy.gif)
