### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by KirstieJane** [INCF/BIDS-Starter-Kit#39]
Possibly inspired by the OHBM demo calls code of conduct? 

https://github.com/ohbm/OpenScienceDemoCalls/blob/master/Code_of_Conduct.md

**Comment by emdupre** [comment]
👍 Definitely ! We can even just adapt from [Contributor Covenant](https://www.contributor-covenant.org/) directly. 

I looked briefly, but didn't see anything-- GSoC doesn't have any resources for this, do they ?

**Comment by dorahermes** [comment]
👍

**Comment by malinsandstrom** [comment]
No, GSoC doesn't have any resources for this AFAIK. I've been considering getting an INCF-GSoC-wide CoC in place, so if you do end up adding a CoC for this project, I would be interested in your experiences and thoughts. (Not sure it is suitable here but I like Kirstie's lab CoC - it is admirably short and readable, which is a factor in GSoC where many students have English as their second/third/fourth language)

**Comment by KirstieJane** [comment]
Sorry I left this for so long! I've submitted a pull request with a version from one of my lab repos: #59. Let me know what you think!! Any and all comments welcome 💖

**Comment by Park-Patrick** [comment]
closing up this issue now that PR #59 is merged!
