### ISSUE TITLE
Clarify repo name

### ISSUE THREAD

**Issue by choldgraf** [INCF/BIDS-Starter-Kit#4]
Here we call it `bids-starter-kit`. But another repo is called `BIDS-examples`. Is it `bids` or `BIDS`? I'm happy w/ either but we should be consistent :-)

**Comment by chrisfilo** [comment]
Sure - I have slight preference to capitalized.

**Comment by KirstieJane** [comment]
(awakening an old issue 😴!)

I like the `starter-kit` part of the name. What about `BIDS-starter-kit`?

(I don't think this would actually make any difference to the repo apart from how we refer to it!)

**Comment by dorahermes** [comment]
I am fine with either. If we change bids to BIDS, sooner would be better than later.

**Comment by Park-Patrick** [comment]
I know this is an old issue, but probably not a huge issue if the main point that needs be discussed is the capitalization.

My opinion is that BIDS makes more sense (because it is an acronym) and I'll change it to `BIDS-starter-kit` at the end of the hackathon, unless there are any disagreements

**Comment by choldgraf** [comment]
sounds good to me - feel free to close this issue when it happens!

**Comment by Park-Patrick** [comment]
Will be closing this soon. Just need to make sure that we're testing / fixing any broken URLs in the process

**Comment by KirstieJane** [comment]
@Park-Patrick - endorsed. Change the formatting and close ✅
