### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by KirstieJane** [INCF/BIDS-Starter-Kit#40]
Possibly inspired by this one from Brain Networks in Python?

https://github.com/WhitakerLab/BrainNetworksInPython/blob/master/CONTRIBUTING.md

**Comment by emdupre** [comment]
We have contributing guidelines now, but they're a re-write of my re-write of your STEMM Role Models guidelines 😆 

So, if you'd like to see changed them to more closely match your Brain Networks in Python guidelines, I think a PR would be great !

**Comment by KirstieJane** [comment]
Ah - I'm so useless. Sorry - I didn't even check first.

I think the [contributing guidelines](CONTRIBUTING.md) need updating though - they focus on submitting pull requests but actually most people will be editing the wiki. Probably just a few additional sentences to explain what's going on and to get people started a little more easily.

**Comment by KirstieJane** [comment]
Heya - I'm going to work on this over the next couple of days at the OHBM hackathon.

Sorry for abandoning it for son long! 😭

**Comment by Park-Patrick** [comment]
Just bumping this up because it should be closed concurrently with PR #63 !
