### ISSUE TITLE
Gitter batch in readme?

### ISSUE THREAD

**Issue by dorahermes** [INCF/bids-starter-kit#46]
Should a link to the Gitter batch be added in the readme? I can't see it right now. @chrisfilo @KirstieJane

**Comment by KirstieJane** [comment]
Heya @dorahermes - I can see the “chat on gitter” badge in the README - it isn’t well aligned but it does show up on the second line as I see it....

**Comment by dorahermes** [comment]
Sorry, thank you, it skipped my eye for some reason. Added a 'For discussions': before the badge.
