### ISSUE TITLE
Incorporate Patrick's GSoC proposal into this repository

### ISSUE THREAD

**Issue by KirstieJane** [INCF/BIDS-Starter-Kit#49]
There are lots of lovely paragraphs explaining why we are building the BIDS Starter Kit in your proposal @Park-Patrick! When you have time I think they'd fit really well into the README 😺

**Comment by KirstieJane** [comment]
@Park-Patrick - given the updates you made to the README file, do you feel like this issue can be closed?

I think the README captures a lot of what you wanted to say, but I think there could be **motivation** or **What's the point of the starter kit** page in the wiki that could incorporate some of the points you made in your application.

What do you think?

**Comment by emdupre** [comment]
Just to chime in, here: I think having a "motivation" section in the wiki would be great. I know a lot of this information is in the [philosophy of the README](https://github.com/incf/bids-starter-kit#philosophy), but I personally feel like this is important enough that I'd rather have it available in too many places than too few ! Obviously happy to be over-ruled, though :smile:

**Comment by Park-Patrick** [comment]
Okay added a motivation section in PR #70 . I think it serves a good purpose in the README as a "why should I care" before the "what is this"

**Comment by KirstieJane** [comment]
This looks great to me @Park-Patrick - happy to close when #70 is merged!
