### ISSUE TITLE
Improvements to this repo before SfN?

### ISSUE THREAD

**Issue by choldgraf** [INCF/bids-starter-kit#5]
I'd like to add a link to this wiki on the SfN poster, and to point people here more generally that want to get started w/ the spec. What other information are we missing? Anything important? I have a few cycles of time to work on this in the next week or two, so wanna make sure it's being spent effectively!

**Comment by dorahermes** [comment]
Would it be useful to have a full iEEG template with all the sidecars with empty fields? I started this, but need to add the _channels.tsv, _electrodes.tsv and _electrods.json templates

**Comment by choldgraf** [comment]
I think a template would be great. In terms of having all the JSON files w/ empty fields, wasn't @chrisfilo working on a JSON schema along these lines? If there's a schema for BIDS, then that's also something we could use (or link to) here.

**Comment by dorahermes** [comment]
@chrisfilo thought that templates should be separate from json schema (schemas can be found in the validator: https://github.com/INCF/bids-validator/tree/master/validators/schemas)

**Comment by choldgraf** [comment]
Yeah that's a fair point. I was more thinking we could *use* the schema in order to generate a template. E.g., just write a script that parses the schema, strips the "description" fields etc, and puts it here. I'm just trying to minimize the number of pieces that move independently of one another.

**Comment by dorahermes** [comment]
I was creating two types of templates: 1) full templates with all optional fields, and 2) minimal templates, with only the required fields. For 2) I think we could potentially use schema files, but I did not see a json schema in the validator for fmap data, so I just started from scratch, see https://github.com/INCF/bids-starter-kit/pull/6

**Comment by choldgraf** [comment]
gotcha - makes sense then!
