### ISSUE TITLE
Integrate already existing resources for learning about BIDS

### ISSUE THREAD

**Issue by KirstieJane** [INCF/BIDS-Starter-Kit#50]
This issue is an easy place to comment if you have made (or know of) useful resources to learn more about BIDS! Please add any and all links - Thank you!! :sparkles:

**Comment by KirstieJane** [comment]
Here’s the twitter thread that inspire this issue :smile:

https://twitter.com/itjohnstone/status/994157844760014849?s=21

**Comment by emdupre** [comment]
I'll add in some resources from our slack channel !

[Patrick's talk ! 🎉 ](https://www.youtube.com/watch?v=LcyCgWQXMDI)

[A graphical representation of BIDS](https://twitter.com/AkiNikolaidis/status/991718858749874176)

[A BIDS App tutorial](https://github.com/fliem/bids_apps_intro)

**Comment by adamshephard** [comment]
Here I have attached a presentation introducing BIDS that I gave at Aston University's Open Science Working Group meeting:

[Brain Imaging Data Structure - OSWG.pptx](https://github.com/INCF/bids-starter-kit/files/2068336/Brain.Imaging.Data.Structure.-.OSWG.pptx)

**Comment by Park-Patrick** [comment]
Thanks @adamshephard! What type of BIDS data do you usually work with?

**Comment by adamshephard** [comment]
Hi Patrick, I usually work with MRI data, hence why the presentation is lacking a bit on the MEG side!

**Comment by Park-Patrick** [comment]
Just continuing on repo housekeeping, it seems like the links to useful resources could be organized into the wiki (with suggestions on how someone could add to it). Happy to hear any thoughts on this! Otherwise I'll go ahead and assign it to myself

**Comment by Park-Patrick** [comment]
New page in the wiki with [community resources](https://github.com/INCF/BIDS-Starter-Kit/wiki/community-resources) !

Just to clarify the intended difference between this page and [Useful Links](https://github.com/INCF/BIDS-Starter-Kit/wiki/Useful-links) , community resources is more for slideshows / talks / graphics and useful links is for code / links to other repos.

Happy to reorganise if this wasn't intuitive for others though
