### ISSUE TITLE
Create glossary for BIDS jargon

### ISSUE THREAD

**Issue by Park-Patrick** [INCF/bids-starter-kit#51]
Some feedback from new users at the BrainHack Western tutorial was that there are too many unfamiliar technical terms associated with BIDS. 
While these terms are needed for accurate communication and consistency, we also see the need for layperson's definitions that are easily understandable.

We imagine this to have two parts:
a) a text (markdown) document on this repo
- i.e. a searchable reference like a traditional glossary
- This document can be continuously growing

b) an easy-to-absorb graphic/video/interactive flashcards
- something visually appealing to cover the important terms

**Comment by Park-Patrick** [comment]
New glossary page created: https://github.com/INCF/bids-starter-kit/wiki/Glossary-(Simple-definitions-for-any-BIDS-related-jargon)

Main reason: Feedback during tutorials indicates that technical jargon makes BIDS adoption harder than it needs to be.
The goal of this page is to provide simple definitions to terms.
For users who are unsure about adding a term/definition, please add it anyway and add an asterix(*) to signal a review.

**Comment by KirstieJane** [comment]
This looks great @Park-Patrick!! I did some formatting. Let me know what you think of it.

I fixed one or two typos but not the definitions! Well done, this is super useful!!

**Comment by KirstieJane** [comment]
That’s my fault @jbpoline - I changed the title & didn’t think how that would affect finding the page.

Here it is: https://github.com/INCF/bids-starter-kit/wiki/Glossary

**Comment by jbpoline** [comment]
Ha - yes - thanks !  I wonder if it would be worth thinking of uri for these definitions in the future.

**Comment by KirstieJane** [comment]
@jbpoline - somewhat ironically given that we're talking about a glossary - I don't know what you mean by uri for these definitions?! Any chance you could expand that point?

**Comment by Park-Patrick** [comment]
@KirstieJane just had to look it up as well -- i think URI is an umbrella term referring to hyperlinks that includes URL, URN, etc. 

Thanks for the typo edits and the comic! (really must be true that there's an XKCD for every situation 😆 ) 

Unless there any more major edits to be made, I'll go ahead and close this issue soon!

**Comment by KirstieJane** [comment]
Yep - this can totally close! Well done!

We could open an “always open” and “help wanted” issue to nudge people to update the glossary - a nudge to inspire people swinging by to check out the glossary and potentially update it - but this one can close 💯
