### ISSUE TITLE
Two small fixes to the func json template

### ISSUE THREAD

**Issue by Park-Patrick** [INCF/bids-starter-kit#52]
The example template file for the bold json file below has a few syntax errors:

https://github.com/INCF/bids-starter-kit/blob/master/templates/sub-01/ses-01/func/sub-01_ses-01_task-ShortExample_run-01_bold.json 

Please help us fix them!

**Hints**

The last line of a json file should not have a comma at the end
The RepetitionFile field must have a numerical value (which doesn't require quotes)
This website can give you helpful feedback about validating your json: https://jsonlint.com/

**Comment by PeerHerholz** [comment]
Hey,

just opened the PR [here](https://github.com/INCF/bids-starter-kit/pull/53).
I hope it's okay.
