### ISSUE TITLE
Link to the BIDS-examples repo

### ISSUE THREAD

**Issue by KirstieJane** [INCF/BIDS-Starter-Kit#56]
I'm not sure I know exactly what the [BIDS-examples](https://github.com/INCF/BIDS-examples) repository is for - I think it's mostly for testing software?

What do you all think about whether we need to link to this repository for the starter kit? Is is distracting? On the other hand it might be good to clarify why it exists 😸

**Comment by Islast** [comment]
I've been using the BIDS-examples repo to test bids apps in my local computer since I don't keep any neuroimaging data there. A lot of the time I want to make sure that software works the way I'm hoping it will before going to the trouble of finding a way to run it on our cluster

**Comment by Park-Patrick** [comment]
Ohh makes sense. So maybe the best way to link there from the starter kit would be something like 
"Want some empty testing data? Link here"

**Comment by Islast** [comment]
@Park-Patrick I've haven't needed them so far but it would be nice to have multi-echo. Not a big priority though, especially since the nii files are empty.

**Comment by emdupre** [comment]
Should this be linked in with #68 ?

**Comment by Park-Patrick** [comment]
Good idea, the BIDS App help page would be a good place to link the testing datasets! done ✔️
