### ISSUE TITLE
Update the README to point very clearly to the wiki

### ISSUE THREAD

**Issue by KirstieJane** [INCF/bids-starter-kit#60]
At the moment the README contains lots of great information and it *does* technically link to the wiki, but I don't think it is very clear that there is LOTS more  information in the wiki!

So somewhere in the README we need to have a section on (something like) "how do I find information" that highlights the wiki (and potentially contains the answer to #57 ✨

**Comment by emdupre** [comment]
What about putting this in project summary ? I think there could be subheadings there !

**Comment by Park-Patrick** [comment]
Fair enough! So under the project summary I'll explicitly mention and link to some of the main subpages in the wiki

**Comment by emdupre** [comment]
I say yes ! At this point, I'd think more (potentially even redundant !) linking is better than too little :smile:

**Comment by Park-Patrick** [comment]
Okay edited! Tagging this now as closing soon to wait for any feedback in the next day or two before closing.
