### ISSUE TITLE
Make a page in the wiki with publications related to BIDS

### ISSUE THREAD

**Issue by KirstieJane** [INCF/BIDS-Starter-Kit#61]
The MEG-BIDS paper was just published this month, but there are more. I think it makes sense to have a page that showcases those papers. They'll be useful to read for anyone getting started, but I think they also lend a little additional oompf as they're peer reviewed and "traditional" publications.

* https://www.nature.com/articles/sdata201644
* https://www.nature.com/articles/sdata2018110

**Comment by Park-Patrick** [comment]
I agree it would be good to showcase those community successes! 
Would it make sense to have 1 or 2  example ones on the README (i.e. under a "BIDS in publication" subheading) and then have a easily editable page in the wiki so that anyone can add more papers?

**Comment by emdupre** [comment]
I think that papers could be listed under "acknowledgments," both to acknowledge the authors (who have already contributed to BIDS !) and to ask that anyone using BIDS consider acknowledging / citing the relevant papers. WDYT ?

**Comment by Park-Patrick** [comment]
Yeah that sounds like a great idea! So I guess it would make sense for us to add the original paper (https://www.nature.com/articles/sdata201644) in the README with a quick comment about citing then?

**Comment by emdupre** [comment]
I'd think so ! Probably both the original and MEG paper, since we're including MEG samples in the code snippets :+1:

**Comment by emdupre** [comment]
I like your idea of the wiki page for people to add more papers, @Park-Patrick -- do you think there we could list publications that *use* BIDS ? It's probably easiest to find those via those using BIDS Apps, but also looking into who has cited the original and the MEG BIDS papers could be a great resource !

**Comment by Park-Patrick** [comment]
The changes are now implemented in the README (PR #70) for the two main papers and there is a more extensible list in the wiki https://github.com/INCF/BIDS-Starter-Kit/wiki/Publications

**Comment by KirstieJane** [comment]
I think this is great - thanks @Park-Patrick.

I'm going to open a "good first issue" asking for help reformatting the references to include the full citation.

@Park-Patrick - don't you work on this, I'll promote it here at neurohackademy in case anyone wants support on their first contribution ❤️
