### ISSUE TITLE
Link to other BIDS-related repositories/tutorials

### ISSUE THREAD

**Issue by gllmflndn** [INCF/BIDS-Starter-Kit#62]
I started documenting some of the BIDS-related functionalities from [SPM](http://www.fil.ion.ucl.ac.uk/spm/) here:
- https://en.wikibooks.org/wiki/SPM/BIDS

which, I thought, could be linked to from the wiki here if you agree.

More generally, I came across these MATLAB functions:
- https://github.com/lorenzomagazzini/mat-meg-bids

and these in Python:
- https://github.com/robertoostenveld/bids
- https://github.com/spinoza-rec/bidsify
- https://github.com/nejaz1/bidsify
- https://github.com/jmtyszka/bidskit
- https://github.com/cbedetti/Dcm2Bids

it seems like BIDS Starter Kit would be the right place to list them all.

**Comment by chrisfilo** [comment]
Super cool!

Best,
Chris

PS Apologies for brevity and potential typos. This message was composed on
a phone.

**Comment by KirstieJane** [comment]
Hey @Park-Patrick - when you're working on #64 please can you also see where these useful links can go?

**Comment by KirstieJane** [comment]
Pinging this issue to @Park-Patrick as it's a good one for this week in the wiki perhaps?

**Comment by Park-Patrick** [comment]
Ok, we have a page for it in the wiki now!


https://github.com/INCF/BIDS-Starter-Kit/wiki/Useful-links

**Comment by KirstieJane** [comment]
Looks great! 👍 💯
