### ISSUE TITLE
Tidy up contents page for the wiki

### ISSUE THREAD

**Issue by KirstieJane** [INCF/bids-starter-kit#64]
At the moment there's a [home page](https://github.com/INCF/bids-starter-kit/wiki) that doesn't say very much and then [BIDS wiki](https://github.com/INCF/bids-starter-kit/wiki/BIDS-Wiki) page that seems to be more of an intro.

As we're making progress on the CONTRIBUTING guidelines (#63) I think it would be great to also make the landing pages of the wiki (along with the contents sidebar etc) really clear about where information can be found.

@Park-Patrick - please can you have a bit of a think about this? Please ping me if you're not sure though, I'm happy to find some time to give feedback etc. Might be something that's easy to do via slack?

**Comment by Park-Patrick** [comment]
Hi @KirstieJane , just finished cleaning up the wiki (i.e. combining the two 
redundant pages and making it more landing page-esque)

Can't really reference a wiki edit here, but take a look at the new page 
and let me know what you think!

**Comment by KirstieJane** [comment]
LOOKS AWESOME!

Well done!! Thank you ✨✨✨
