### ISSUE TITLE
Document process / compile FAQ for creating BIDS Apps

### ISSUE THREAD

**Issue by Park-Patrick** [INCF/BIDS-Starter-Kit#68]
Working together with Daniele, Asier and Madhur to document the process of creating a BIDS app. 
This will most likely be a page on the wiki!

**Comment by emdupre** [comment]
Excited to see this documented ! Just to add one helpful resource: there's [example BIDS App](https://github.com/BIDS-Apps/example) repository

**Comment by Park-Patrick** [comment]
Thanks for the helpful link!

Check out the new wiki page and let me know what you think:
https://github.com/INCF/BIDS-Starter-Kit/wiki/BIDS-Apps-Help

**Comment by KirstieJane** [comment]
This looks great @Park-Patrick! I made a few changes (a little bit of formatting and a couple of new links) but definitely looks awesome ✨
