### ISSUE TITLE
Edit contents of wiki sidebar

### ISSUE THREAD

**Issue by Park-Patrick** [INCF/BIDS-Starter-Kit#69]
At the moment, the _Sidebar file in the wiki lists the various pages, but this is redundant with the Pages tab. Mostly this creates some issues when a new page is added / deleted because two different table of contents have to be updated separately. 

We can brainstorm about what info would be useful there (i.e. whatever would be good to have displayed on the side of every wiki page) or leave it minimal for now

**Comment by emdupre** [comment]
What about the "Relevant links in the BIDS ecosystem" box ? These seem to appear on every page as well !

**Comment by KirstieJane** [comment]
I haven't yet developed my strong opinions about these boxes, but I think I do like the sidebar and I think the relevant links could be useful.....

HOWEVER, I don't like that they aren't being used particularly well at the moment....

What I really like about the sidebar is that you can annotate the entries, and that it is unfolded by default. So a really clear set of links on the right could be worth its weight in gold if well considered.

I think I'd get rid of the relevant links box for now.

Happy to hear what others think!

**Comment by Park-Patrick** [comment]
Okay happy to leave the sidebar as is!

Re the footer : Realised while deleting it that it would probably be the most appropriate place to link the contributing guidelines and contact page (since it appears at the bottom of every page)

Once again.. no pull request that I can link to, but changes are implemented in the wiki

**Comment by KirstieJane** [comment]
✨ Awesome 👾 
Thanks @Park-Patrick

**Comment by KirstieJane** [comment]
I'm just looking at the sidebar - you've gone for alphabetical order, right?

My gut instinct is that it would make more sense to align it with the most immediately useful links near the top (basically very similarly inspired by your thinking in #71).

Do you feel strongly about alphabetical order?

**Comment by Park-Patrick** [comment]
Alphabetical was just what I defaulted to, but I guess it makes more intuitive sense to have tutorials higher than BIDS Apps for example.

I'll go ahead and rearrange in a roughly priority based order, but feel free to rearrange any links!
