### ISSUE TITLE
Incorporate the bids validator into the wiki

### ISSUE THREAD

**Issue by KirstieJane** [INCF/BIDS-Starter-Kit#77]
I'm not sure if it should be a new page (my gut instinct) or a page that has a few other bits of information, but I think it's useful to include a description of the validator: http://incf.github.io/bids-validator.

* What it does
* Why its useful
* What it *doesn't* do (upload data!)
* How it works? (maybe not too necessary)
* Some example outputs (most importantly 🌟)

**Comment by Park-Patrick** [comment]
added! https://github.com/INCF/BIDS-Starter-Kit/wiki/bids-validator-info
