### ISSUE TITLE
Upload some non-BIDSified data to the BIDS Examples repo or document where to find some

### ISSUE THREAD

**Issue by KirstieJane** [INCF/BIDS-Starter-Kit#79]
In his [tutorials](http://reproducibility.stanford.edu/bids-tutorial-series-part-1a/), Franklin uses data from the NKI Rockland sample to show an example of not-yet-bidsified data.

I think these resources would be super useful to document in the starter kit. Any ideas?

**Comment by emdupre** [comment]
Sorry, to confirm, is the goal to point to "practice data" for BIDS conversion ?

Either way, [FCON 1000](http://fcon_1000.projects.nitrc.org/fcpClassic/FcpTable.html) is another great resource !

**Comment by chrisfilo** [comment]
Why not figshare?

Best,
Chris

PS Apologies for brevity and potential typos. This message was composed on
a phone.

**Comment by KirstieJane** [comment]
I'd go with @Park-Patrick's idea of linking clearly if the data is already stored somewhere.

The point is to make it super easy to follow along with Franklin's tutorials by yourself 😄

**Comment by Park-Patrick** [comment]
done ✔️ 

https://github.com/INCF/BIDS-Starter-Kit/wiki/Dataset-Examples
