### ISSUE TITLE
R information to the meta-data wiki

### ISSUE THREAD

**Issue by Athanasiamo** [INCF/bids-starter-kit#8]
As requested by @chrisfilo , I'm doing this as an issue as I can't contribute to the wiki. Here's some markdown regarding writing and reading .json and .tsv files from R. 

## R
There are several packages for reading and writing JSON files from R. In this example we will be using jsonlite. Remember to install and call a package before using it.

https://github.com/jeroen/jsonlite

### Installing required package
```r
install.packages('jsonlite')
```

### Reading a `.json` file
```r
library(jsonlite)
data = fromJSON('myfile.json', pretty=TRUE)
```

### Writing a `.json` file
```r
library(jsonlite)
data = {'field1': 'value1', 'field2': 3, 'field3': 'field3'}
writeLines(toJSON(data, pretty=TRUE), file="myData.json")
```

## R
Reading and writing tab separated files comes natively in R, no need for extra packages. 

### Reading a `.tsv` file
In this example, we assume the .tsv includes column names (headers), and explicitly set column separator (delimitor)  to tab ('\t')

```r
data = read.table('myFile.tsv', header=TRUE, sep='\t')
```

### Writing a `.tsv` file
When writing files, colum and row names are always saved, we remove row names, and quotes from the outpur explicitly by setting them to FALSE. 
```r
data = cbind.data.frame(
  participant_id = c('sub-01', 'sub-02'),
  age = c(20,30),
  sex = c('m','f'))

write.table(data, file='myData.tsv',sep='\t',
  row.names = FALSE, quote = FALSE)
```

**Comment by choldgraf** [comment]
This is great! The only extra thing I'd recommend is to link out to some other tutorial(s) w/ more information for people that want to dig a bit deeper (since this page is for beginner-types). But I don't think that should block on this content being added.

**Comment by choldgraf** [comment]
also, we're discussing how to let people contribute to the wiki here: #7 in case you've got thoughts!

**Comment by chrisfilo** [comment]
Thank you for sending this. I will let @choldgraf and @dorahermes review and integrate it into the wiki.

**Comment by Athanasiamo** [comment]
@choldgraf you mean link to more information regarding writing and working with json-files? Jeroen links to his vignettes on the jsonlite package from the github repo i added a link to, which should give you what you need to get more into it?

Or, the simplest way to do this, technically, is using leeper's rio package, that just uses the file extension given to infer fie type. It has great documentation: https://github.com/leeper/rio . 

But, it's a large package, and I opted for the solutions that required minimal installation.

**Comment by dorahermes** [comment]
Thank you for adding the R instructions! I integrated these in the wiki, let me know if you have any other additions.

**Comment by Athanasiamo** [comment]
You're welcome, but I made a small error! Please, change the writing .json files part to this:

```r
data = '{"field1": "value1", "field2": 3, "field3": "field3"}'
writeLines(data, file="myData.json")
````

Had missed on some quotation marks in making the data, and since the data is already in json format, you dont need to call "toJSON" when saving it. Sorry about that.

**Comment by dorahermes** [comment]
Thanks for checking, it's fixed.
Issue #7 will be an important one to tackle.
