### ISSUE TITLE
potentially incorrect link for help on issues

### ISSUE THREAD

**Issue by bayab** [INCF/BIDS-Starter-Kit#85]
In the README.md file, under the 'Contributing' section, there's a link for 'using issues', but it leads to the same page (the link is currently https://github.com/INCF/BIDS-Starter-Kit#where-to-start-issue-labels, perhaps it should be https://github.com/INCF/BIDS-Starter-Kit/blob/master/CONTRIBUTING.md#where-to-start-issue-labels ?)
It may also be helpful to add a link there github's help on issues.

**Comment by KirstieJane** [comment]
Ooooh yes! Great catch @bayab!

Do you want to submit a pull request to fix the link and add a link to the github help?

**Comment by bayab** [comment]
Sure, no time like the present for my first pull request :)

**Comment by KirstieJane** [comment]
Woooo hooo! Let me know if you have any questions ✨

**Comment by bayab** [comment]
I noticed the link for 'pull request' also seemed to be incorrect, so fixed that too (if this indeed worked?)

**Comment by KirstieJane** [comment]
✨ Woooo hooo! 👾
