### ISSUE TITLE
Repo Format

### ISSUE THREAD

**Issue by emdupre** [INCF/bids-starter-kit#9]
Branching off of #7, is there an opinion on moving the repo format to a series of ipython/binder notebooks?  I'm thinking something similar to what [nipype has for their tutorials](https://miykael.github.io/nipype_tutorial/). 

It seems as though this would be a good fit, as right now code snippets in [R/matlab/python] are being included in the wiki and could be instead executed in the notebooks. This might make it easier for new adopters to play around with the code themselves.

**Comment by dorahermes** [comment]
When we setup this repo, we wanted to have a wiki also for people with very little or no coding experience (note that there are instructions for excell generation of .tsv files and online json editing). We thus thought that code, say if it's more than a snipet, should go into the repo, and be separate for Matlab/Python/R etc. The wiki can link to code. For example, the wiki could give a brief list of which files should be generated as metadata for a (for example) resting state fMRI dataset (see 'The BIDS Folder Hierarchy'). Then there can be links to examples in Python/Matlab/R that generate empty metadata files and structures. This initial structure depends on issue #7 and suggestions are welcome!!

**Comment by Athanasiamo** [comment]
I think both wiki and notebooks are a good idea, and see the value of both, and would welcome any of the two options really, as a user. 

I don't think notebooks are particularly scary for people with little or no coding experience, as long as they are well annotated and start off easily. It could provide some hands-on experience that might get someone just comfortable enough to give it a go them selves. 

While the wiki is good for people just wanting information, without really wanting/needing hands-on experience. Perhaps they are applying for funding to dedicate resources to implement BIDS for their datasets, and a link to a wiki would then be more valuable than notebooks.  

I guess, it might make sense to have both, though that might require more maintenance. A wiki for information, that may link to tutorial notebooks?

**Comment by KirstieJane** [comment]
+1 to all the comments above - and for forking this discussion into a different issue!

I love the idea of building up a few lightweight mybinder enabled notebooks! :100:

Also makes sense if we do decide to have a wiki for the documentstion to have some content in the repo itself - and some notebooks that immediately take you through examples are perfect places to start!

**Comment by KirstieJane** [comment]
I feel like - given @dorahermes' [comment](https://github.com/INCF/bids-starter-kit/issues/7#issuecomment-355335959) on #7 and the associated updates to README we can probably close this issue? @emdupre - do you feel like we've reached a consensus?
